### ISSUE TITLE
Citación recomendada

### ISSUE THREAD

**Issue by morethanbooks** [arojascastro/soledades#7]
Creo que en el archivo de documentación en la raíz debería haber una recomendación sobre cómo citar la edición. Aparecen diferentes artículos relacionados, pero no cómo citar la edición en sí.

Venga, va Antonio, que es una línea de texto! ;)

**Comment by arojascastro** [comment]
Holis, ahora mismo la única edición que está disponible es esta: http://soledades.uni-koeln.de/#/critical?d=doc_1&e=critical

Esta la tengo que actualizar pronto para optimizar unos problemillas pero estoy a la espera de la versión 3 de EVT. 

Las otras dos ediciones... pues una jamás la publiqué y la anotada estuvo disponible en www.soledadesediciondigital.com/ pero en estos momentos no es accesible porque la estoy adaptando para moverla github y visualizarla de otra manera. 

En fin, que lo único que puedes citar verdaderamente es la crítica:

Góngora, Luis de. 2017. «Soledades» de Luis de Góngora. Edición crítica digital. Ed. de Antonio Rojas Castro. Cologne Center for eHumanities (CCeH). <http://soledades.uni-koeln.de/#/critical?d=doc_1&e=critical>

**Comment by morethanbooks** [comment]
Estupendo, gracias!

**Comment by arojascastro** [comment]
Se me olvidó mencionar que la edición actual de la crítica es la 2ª ed. de 2017; si no recuerdo mal, la primera edición es de 2016 que publiqué con la primera versión de EVT (la tesis la leí en noviembre de 2015). Es decir, cada versión cambia según cambia cada versión de EVT. La tercera edición, pues, espero que salga en 2020 pero no sé.
